README.md First Edition
tenzyu/simple-controller pull request #1
Opened 2021-01-24 12:51 UTC by tenzyu

2021-01-24 12:52 UTC, tenzyu commented
you can preview markdown [here](https://github.com/tenzyu/simple-controller/blob/3faa4dccdcde6d7a7e37686b9422c76eac62ff08/README.md)

2021-01-24 15:47 UTC, Kesigomon requested changes

2021-01-24 15:47 UTC, Kesigomon commented on README.md
> +- Editor: Visual Studio Code
Pycharm追加して♡

2021-01-24 15:59 UTC, tenzyu commented on README.md
> +- Editor: Visual Studio Code
ok

2021-01-24 16:01 UTC, tenzyu commented
実は、他のSimpleBotsのプライマリ言語を英語から日本語に変更したので、これも書き換えようと思う。

2021-01-24 16:07 UTC, tenzyu commented
日本語に書き換えてみたので読んで違和感があるところを教えてください。

2021-01-24 16:14 UTC, Kesigomon approved these changes
![0001](https://user-images.githubusercontent.com/34025522/105636194-99a34f00-5eaa-11eb-9578-11c00b640e49.png)
LGTM!

2021-01-25 06:02 UTC, tenzyu commented
一応プレビュー再掲
https://github.com/tenzyu/simple-controller/blob/146d75adf126431c21720ef3a11ac157c5c6a6dc/README.md
ぽちぽちしまくってみにいくの面倒だしね

2021-01-25 07:27 UTC, AttoCat approved these changes
良いと思います。

2021-01-25 07:27 UTC, merged