Add command to delete the channel
tenzyu/simple-controller pull request #11
Opened 2021-01-28 07:18 UTC by tenzyu

2021-01-28 07:29 UTC, tenzyu commented
```py
    @channel.command(name="delete", aliases=["del"])
    @has_permissions(manage_channels=True)
    async def _delete(self, ctx: Context, *, reason: str = None):
```

`?channel del <reason>` を受け取る
本当にチャンネルを削除するかどうか確認する
`y` が返ってきたら削除

2021-01-28 07:34 UTC, AttoCat commented
確認、たくさん使うことになりそうだからモジュールで定義したいね

2021-01-28 07:36 UTC, tenzyu commented
それはそう
このブランチでやれってこと？

2021-01-28 07:53 UTC, tenzyu commented
切り出してモジュール化は初めてなので、コードレビュー頼みます。

2021-01-28 15:28 UTC, Kesigomon requested changes

2021-01-28 15:28 UTC, Kesigomon commented on utils/confirm.py
> +    async def dialog(ctx, what: str):
インスタンスメソッドの第１引数は、インスタンス自身を指定するべきなので、メソッドの書き方としては良くないかなぁ
namedtupleとか使うと良さそう？

2021-01-28 15:28 UTC, Kesigomon commented on utils/confirm.py
> +    async def dialog(ctx, what: str):
それかインスタンス初期化時にctx取るっていうのもありか。

2021-01-29 12:07 UTC, AttoCat commented on utils/confirm.py
> +    async def dialog(ctx, what: str):
データクラスを使うと幸せになれるかも？

2021-01-29 22:40 UTC, tenzyu commented on utils/confirm.py
> +    async def dialog(ctx, what: str):
スタティックメソッドで書くなどする予定

2021-01-30 09:58 UTC, tenzyu commented
コンフリクト解消しました。

2021-01-30 16:44 UTC, Kesigomon approved these changes
![0001](https://user-images.githubusercontent.com/34025522/105636194-99a34f00-5eaa-11eb-9578-11c00b640e49.png)
LGTM!

2021-01-31 12:18 UTC, AttoCat approved these changes
LGTM!!

2021-01-31 12:19 UTC, merged