two-character aliasing
tenzyu/simple-controller pull request #19
Opened 2021-03-18 08:19 UTC by tenzyu

2021-03-18 09:13 UTC, Hirosukee approved these changes
これいる？

2021-03-18 09:20 UTC, tenzyu commented
全部2文字ならまだ規則的なのと、例えば`!ch `で4文字打たせた上で他とも重複せず打ちやすいのは2文字だと思う。

2021-03-19 08:30 UTC, Kesigomon requested changes

2021-03-19 08:30 UTC, Kesigomon commented on cogs/text_channel.py
> -    @channel.command(aliases=["del"])
個人的体感だけど、ここはdelのままのほうがいいかなー

2021-03-19 09:03 UTC, tenzyu commented on cogs/text_channel.py
> -    @channel.command(aliases=["del"])
category を cat から ca と略すようになった記憶があるので、全て2文字で統一したい。
複数設定するのもあまり好みではないのだけれど、["de", "del"] にしたほうがいいのかな。

2021-03-19 09:22 UTC, Kesigomon commented on cogs/text_channel.py
> -    @channel.command(aliases=["del"])
まぁこの辺はセンスなのでおまかせします

2021-03-19 09:33 UTC, tenzyu commented on cogs/text_channel.py
> -    @channel.command(aliases=["del"])
https://github.com/tenzyu/simple-controller/pull/19/commits/24ed8d9a315eb5b1d662dee6419644c05749fc2b で修正

2021-03-19 09:39 UTC, Kesigomon approved these changes
![0001](https://user-images.githubusercontent.com/34025522/105636194-99a34f00-5eaa-11eb-9578-11c00b640e49.png)
LGTM!

2021-03-19 09:46 UTC, merged