added command edit channel topic
tenzyu/simple-controller pull request #20
Opened 2021-03-18 08:25 UTC by tenzyu

2021-03-18 09:11 UTC, Hirosukee approved these changes
これいる？

2021-03-18 09:22 UTC, tenzyu commented
機能乗せても不都合ないのと、simple controller で操作することが増えるとコマンドでトピック変えることもありそう。オレは欲しいので書いた。

2021-03-19 08:56 UTC, Kesigomon requested changes

2021-03-19 08:56 UTC, Kesigomon commented on cogs/text_channel.py
> +        await ctx.reply(f"チャンネルのトピックを {ctx.channel.topic} に変更しました。")
BOTにeveryone権限あるとこのコマンド利用してeveryone打てちゃうな

2021-03-19 09:09 UTC, tenzyu commented on cogs/text_channel.py
> +        await ctx.reply(f"チャンネルのトピックを {ctx.channel.topic} に変更しました。")
https://github.com/tenzyu/simple-controller/pull/20/commits/3cae547547dede1bce9125652769c502727b049b で修正

2021-03-19 09:39 UTC, Kesigomon approved these changes
![0001](https://user-images.githubusercontent.com/34025522/105636194-99a34f00-5eaa-11eb-9578-11c00b640e49.png)
LGTM!

2021-03-19 09:47 UTC, merged