added create webhook command
tenzyu/simple-controller pull request #21
Opened 2021-03-18 08:34 UTC by tenzyu

2021-03-18 09:11 UTC, Hirosukee approved these changes

2021-03-18 09:11 UTC, Hirosukee commented
いいね

2021-03-19 08:31 UTC, Kesigomon requested changes

2021-03-19 08:31 UTC, Kesigomon commented on cogs/text_channel.py
> +        await ctx.author.send(
DMが送れなかった時の対応はなんか書いたほうがいいかも？

2021-03-19 09:13 UTC, tenzyu commented on cogs/text_channel.py
> +        await ctx.author.send(
https://github.com/tenzyu/simple-controller/pull/21/commits/bd24d531ea9af0f4fff701325240aa8d4ad61a61 で修正

2021-03-19 09:36 UTC, Kesigomon requested changes

2021-03-19 09:36 UTC, Kesigomon commented on cogs/text_channel.py
> +        except Exception:
エラー広すぎ大臣さんしてる

2021-03-19 09:46 UTC, tenzyu commented on cogs/text_channel.py
> +        except Exception:
https://github.com/tenzyu/simple-controller/pull/21/commits/8b23f6d63c814d0d0bf01972c8d62f626e0ef5ba で修正

2021-03-19 09:56 UTC, Kesigomon approved these changes
![0001](https://user-images.githubusercontent.com/34025522/105636194-99a34f00-5eaa-11eb-9578-11c00b640e49.png)
LGTM!

2021-03-19 09:58 UTC, Kesigomon commented
コンフリクトしてるやんけ（こなみ）

2021-03-19 09:59 UTC, tenzyu commented
> コンフリクトしてるやんけ（こなみ）

毎回直してるから大丈夫よ

2021-03-19 10:10 UTC, merged