added unpin all command
tenzyu/simple-controller pull request #22
Opened 2021-03-18 08:41 UTC by tenzyu

2021-03-18 09:10 UTC, Hirosukee approved these changes

2021-03-18 09:10 UTC, Hirosukee commented
いいね

2021-03-19 08:32 UTC, Kesigomon requested changes
危険なコマンドな感じはするから確認は入れたほうがいいかな

2021-03-19 09:18 UTC, tenzyu commented
> 危険なコマンドな感じはするから確認は入れたほうがいいかな

https://github.com/tenzyu/simple-controller/pull/22/commits/7b5e7c58005ceac82e82e945eaa01e4bd856eeff で修正
@Kesigomon

2021-03-19 09:40 UTC, Kesigomon approved these changes
![0001](https://user-images.githubusercontent.com/34025522/105636194-99a34f00-5eaa-11eb-9578-11c00b640e49.png)
LGTM!

2021-03-19 09:48 UTC, merged