added bot invite command
tenzyu/simple-controller pull request #23
Opened 2021-03-18 08:47 UTC by tenzyu

2021-03-18 09:02 UTC, Hirosukee commented
いいと思います

2021-03-18 09:04 UTC, Hirosukee approved these changes

2021-03-19 08:58 UTC, Kesigomon requested changes

2021-03-19 08:58 UTC, Kesigomon commented on cogs/utilities.py
> +        url = "https://discord.com/api/oauth2/authorize?client_id=802867226700677120&permissions=8&scope=bot"
ここのclient_idってBOTのIDそのものだからそっちのほうが良さそう

2021-03-19 08:59 UTC, tenzyu commented on cogs/utilities.py
> +        url = "https://discord.com/api/oauth2/authorize?client_id=802867226700677120&permissions=8&scope=bot"
聞いたことあるけど実はよくわかっていないです。
f-strings にして、{self.bot.id} とかにするって話ですか？

2021-03-19 09:58 UTC, Kesigomon commented on cogs/utilities.py
> +        url = "https://discord.com/api/oauth2/authorize?client_id=802867226700677120&permissions=8&scope=bot"
そう、それでいけるはず

2021-03-19 10:09 UTC, tenzyu commented on cogs/utilities.py
> +        url = "https://discord.com/api/oauth2/authorize?client_id=802867226700677120&permissions=8&scope=bot"
https://github.com/tenzyu/simple-controller/pull/23/commits/38435eea858493c8c76da6b1ce384795b47834d8 こっちでどうですか？

2021-03-19 10:17 UTC, tenzyu commented
https://github.com/tenzyu/simple-controller/pull/23/commits/96d440c166c100563b9a1cfe9717bae067317d35 間違えました…

2021-03-19 11:08 UTC, Kesigomon commented on cogs/utilities.py
> +        url = "https://discord.com/api/oauth2/authorize?client_id=802867226700677120&permissions=8&scope=bot"
良いんじゃないでしょうか

2021-03-19 11:14 UTC, Kesigomon approved these changes
![0001](https://user-images.githubusercontent.com/34025522/105636194-99a34f00-5eaa-11eb-9578-11c00b640e49.png)
LGTM!

2021-03-19 11:19 UTC, merged