added category purge command
tenzyu/simple-controller pull request #25
Opened 2021-03-18 09:17 UTC by tenzyu

2021-03-18 09:17 UTC, Hirosukee approved these changes
便利だよね

2021-03-19 09:26 UTC, Kesigomon requested changes

2021-03-19 09:26 UTC, Kesigomon commented on cogs/category_channel.py
> +            except Exception:
Exceptionじゃ広すぎるから、AttributeErrorにしたほうがいいかも

2021-03-19 09:26 UTC, Kesigomon commented on cogs/category_channel.py
> +                await ctx.reply("カテゴリーを指定してください。")
return忘れてない？

2021-03-19 09:26 UTC, Kesigomon commented on cogs/category_channel.py
> +        except Exception:
これもエラーが広すぎる

2021-03-19 09:31 UTC, tenzyu commented on cogs/category_channel.py
> +            except Exception:
https://github.com/tenzyu/simple-controller/pull/25/commits/3500310bbd20463e58a523fac686001c0ed35095　で修正

2021-03-19 09:32 UTC, tenzyu commented on cogs/category_channel.py
> +        except Exception:
https://github.com/tenzyu/simple-controller/pull/25/commits/a157e13f19bf520dd329013d3505fe6f18b9f74e で修正

2021-03-19 09:32 UTC, tenzyu commented on cogs/category_channel.py
> +                await ctx.reply("カテゴリーを指定してください。")
https://github.com/tenzyu/simple-controller/pull/25/commits/6463b7d8242fa2060b9722ee08febcdbaf086317　で修正

2021-03-19 09:39 UTC, Kesigomon approved these changes
![0001](https://user-images.githubusercontent.com/34025522/105636194-99a34f00-5eaa-11eb-9578-11c00b640e49.png)
LGTM!

2021-03-19 09:48 UTC, merged