Added purge and purgeall command
tenzyu/simple-controller pull request #5
Opened 2021-01-25 09:29 UTC by tenzyu

# ?purge N and ?purgeall
みぃ様と同じ使用感で、Embedで完了通知してくれるようにしています。

リファクタリング頼みます。

2021-01-25 14:26 UTC, Kesigomon requested changes

2021-01-25 14:26 UTC, Kesigomon commented on cogs/manage_messages.py
> +        """全てのメッセージを一括削除します。"""
パージオールって危険なコマンドだから
実行時に本当に消してもよいかの確認追加したほうが良さそう

2021-01-25 14:51 UTC, tenzyu commented on cogs/manage_messages.py
> +        """全てのメッセージを一括削除します。"""
https://github.com/tenzyu/simple-controller/pull/5/commits/feee1cfbcb4510c9342f8fdf16ded147bd17a1c2

2021-01-25 14:56 UTC, Kesigomon approved these changes
![0001](https://user-images.githubusercontent.com/34025522/105636194-99a34f00-5eaa-11eb-9578-11c00b640e49.png)
LGTM!

2021-01-26 11:59 UTC, tenzyu commented
エラー周り地獄です　とりあえずパージ機能だけは動きます

2021-01-27 09:09 UTC, AttoCat approved these changes
問題ないと思います。
エラー文に必要な権限を書いてあげると親切な気がするので、そのうちやろうと思います。

2021-01-27 15:08 UTC, merged